#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
LIST=$( git diff --name-only --cached --diff-filter=ACM -- *.{yml,yaml} )

if [ -n "$LIST" ]; then
		node_modules/yaml-lint/cli.js $LIST
fi
